import FramerLazyMotion from "@/components/FramerLazyMotionProvider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TanstackQueryClientProvider from "@/components/TanstackQueryClientProvider";

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <FramerLazyMotion>
        <TanstackQueryClientProvider>
          <body className={`${pretendard.variable}`}>{children}</body>
        </TanstackQueryClientProvider>
      </FramerLazyMotion>
    </html>
  );
}
